// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5PXleS0_cY0EzQAye5pRQn-_eqHlFa2U',
    appId: '1:987815053403:web:866b300e2e2a570128177e',
    messagingSenderId: '987815053403',
    projectId: 'sela-app-ce1dc',
    authDomain: 'sela-app-ce1dc.firebaseapp.com',
    storageBucket: 'sela-app-ce1dc.appspot.com',
    measurementId: 'G-06ECGT6143',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-4m5CAlylA9TBnmOC_gD0t3_AL59svbQ',
    appId: '1:987815053403:android:18702246cdc25c1028177e',
    messagingSenderId: '987815053403',
    projectId: 'sela-app-ce1dc',
    storageBucket: 'sela-app-ce1dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0RxfO6N8jTqi2Zg9K5qMkXwViYcAiF9o',
    appId: '1:987815053403:ios:b02d29c70dc1a2d128177e',
    messagingSenderId: '987815053403',
    projectId: 'sela-app-ce1dc',
    storageBucket: 'sela-app-ce1dc.appspot.com',
    androidClientId: '987815053403-nhvr69k0lvk9lgloukqj7s74te256msr.apps.googleusercontent.com',
    iosClientId: '987815053403-jpi70eu7pna778r03bck03p0e6cnvldi.apps.googleusercontent.com',
    iosBundleId: 'com.example.sela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0RxfO6N8jTqi2Zg9K5qMkXwViYcAiF9o',
    appId: '1:987815053403:ios:b02d29c70dc1a2d128177e',
    messagingSenderId: '987815053403',
    projectId: 'sela-app-ce1dc',
    storageBucket: 'sela-app-ce1dc.appspot.com',
    androidClientId: '987815053403-nhvr69k0lvk9lgloukqj7s74te256msr.apps.googleusercontent.com',
    iosClientId: '987815053403-jpi70eu7pna778r03bck03p0e6cnvldi.apps.googleusercontent.com',
    iosBundleId: 'com.example.sela',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5PXleS0_cY0EzQAye5pRQn-_eqHlFa2U',
    appId: '1:987815053403:web:d7177529809f538e28177e',
    messagingSenderId: '987815053403',
    projectId: 'sela-app-ce1dc',
    authDomain: 'sela-app-ce1dc.firebaseapp.com',
    storageBucket: 'sela-app-ce1dc.appspot.com',
    measurementId: 'G-E4GF06ZM5J',
  );
}
